### ISSUE TITLE
[Next] TODO list for the next major version (1.x.x)

### ISSUE THREAD

**Issue by icebob** [icebob/fastest-validator#92]
# Fully rewritten codebase
- [x] Entire codebase will be rewritten. Compiler will make the source code of the check function and compile it with `new Function`.

# New `equal` type
- [x] It checks the value equal (`==`) to a static value or another property. The `strict` property uses `===` to check values.

```js
{
    password: { type: "string", min: 6 },
    confirmPassword: { type: "equal", field: "password", strict: true } // strict means `===`
}
```

```js
{
    agreeTerms: { type: "equal", value: true }
}
```

# Enhanced shorthand types
- [x] Using rule properties in string shorthand definition.
```js
{
    password: "string|min:6" // additional properties
    age: "number|optional|integer|positive|min:0|max:99", // additional properties

    retry: ["number|integer|min:0", "boolean"] // multiple types
}
```

# Compile async validator
- [ ] It compiles an async validator function which returns a Promise. On the other hand, it adds a new `customAsync` custom rule.
```js
const check = validator.compileAsync({
    username: { type: "customAsync", async check(value) { /* .... */} }
});

check(obj).then(res => {
    // Sanitized obj
}).catch(errors => {
    console.log(errors);
});
```

# Sanitizations
Some common sanitization features. It modifies the original object!

- [x] **convert strings to numbers**
  ```js
  age: { type: "number", convert: true }
  ```
- [x] **convert strings & numbers to booleans**
  ```js
  age: { type: "boolean", convert: true }
  ```
- [x] **convert strings to dates**
  ```js
  age: { type: "date", convert: true }
  ```
- [x] **trim strings**
  ```js
  name: { type: "string", trim: true }
  ```
- [x] **left-trim strings**
  ```js
  name: { type: "string", trimLeft: true }
  ```
- [x] **right-trim strings**
  ```js
  name: { type: "string", trimRight: true }
  ```
- [x] **lowercase strings**
  ```js
  name: { type: "string", lowercase: true }
  ```
- [x] **uppercase strings**
  ```js
  name: { type: "string", uppercase: true }
  ```
- [x] **locale lowercase strings**
  ```js
  name: { type: "string", localeLowercase: true }
  ```
- [x] **locale uppercase strings**
  ```js
  name: { type: "string", localeUppercase: true }
  ```
- [x] **normalize emails** (lowercase, ...)
  ```js
  name: { type: "email", normalize: true }
  ```
- [x] **left padding**
  ```js
  name: { type: "string", padStart: 5, padChar: " " }
  ```
- [x] **right padding**
  ```js
  name: { type: "string", padEnd: 5, padChar: "0" }
  ```
- [x] **convert (date, number, boolean) to string**
  ```js
  name: { type: "string", convert: true }
  ```
- [x] **default value** (if `undefined` or `null`)
  ```js
  role: { type: "string", optional: true, default: "user" }
  ```
- [x] **remove forbidden properties if `remove: true`**
- [x] **remove extra properties if `strict: "remove"`**

**Comment by Snelius30** [comment]
What about some deps? I mean if we have two params and both can be empty but not in same time.

**Comment by dehypnosis** [comment]
what do you think about custom sanitization function feature?

**Comment by icebob** [comment]
Do you have any idea, how it would work?

**Comment by dehypnosis** [comment]
```js
phoneNumber: {
  type: "phone",
  types: ["mobile", "fixed-line-or-mobile"], // default
  country: "KR" // default
}
```
For example, above schema validates phone number format by below custom validation rule.

```js
validator.add("phone", ({ schema, messages }: any, field: any, context: any) => {
  context.PhoneNumber = PhoneNumber;
  context.types = schema.types || ["mobile", "fixed-line-or-mobile"];
  context.country = schema.country || "KR";
  return {
    source: `
      if (typeof value === "string") {
        const sanitizedValue = value.replace(/[^0-9+]/g, " ").split(" ").filter((s) => !!s).join("")
        const phoneNumberObj = new context.PhoneNumber(value, context.country); // TODO: i18n; country code from context
        if (phoneNumberObj.isPossible() && context.types.includes(phoneNumberObj.getType())) {
          return phoneNumberObj.getNumber("international");
        }
      }
      ${validator.makeError({ type: "invalidPhoneNumber", actual: "value", messages })}
    `,
  };
});
```

Above custom rule function returns sanitized value, not the original input.
```
          return phoneNumberObj.getNumber("international");
```

Shortly, if just returns modified value from rule function, it is affected to original validation payload.
Isn't it your intended feature?

**Comment by icebob** [comment]
Yes, the rules can modify the value which affects the original payload. This is why the version changed to 1.0.0 because it is a breaking change.
